language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules

script:
  - yarn test:ci
  - yarn build

deploy:
  provider: npm
  email: $NPM_USER
  api_key: $NPM_API_KEY
  on:
    tags: true
